# This is a basic workflow that is manually triggered
# ワークフロー名の設定
name: Gatsby build and deploy to a server

# master branch へ push したときにこのワークフローを実行するよう指定
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true
  
# 以下，jobs の定義
jobs:
  # 「build」という名前のジョブを定義
  build:
    # ubunts の最新版を指定
    runs-on: ubuntu-20.04
    strategy:
          matrix:
            node-version: [16.x, 18.x]
    # 実行する処理やコマンドを指定
    steps:
      # レポジトリからの checkout を実行
      - uses: actions/checkout@v3
      # Node のセットアップ
      # - name: Use Node.js ${{ matrix.node-version }}
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: ${{ matrix.node-version }}
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
      # Node の実行（yarn install, yarn run build）
      - name: Build Project
        run: |
          yarn
          yarn run build
      # npm の場合は以下
        # npm install
        # npm run build
      # 確認のためのリスト表示　必要なければ削除
      # - name: List output files
      #   run: ls -laFG
      #
      # 以下のサイトを参考に github action で build, netlify へ publicフォルダを転送
      # https://sung.codes/blog/2019/12/25/building-gatsby-with-git-hub-actions-and-deploying-to-netlify/
      # - name: Publish using netlify
      #   uses: netlify/actions/cli@master
      #   with:
      #     args: deploy --dir=public --prod
      #   env:
      #     NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      #     NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './public'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
      # rsync の設定
      - name: rsync deployments to hlc1
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --omit-dir-times --delete
          path: public/
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.ID_ECDSA_FREEDOM }}
