# This is a basic workflow that is manually triggered
# ワークフロー名の設定
name: Gatsby build and deploy to a server

# master branch へ push したときにこのワークフローを実行するよう指定
on:
  push:
    branches:
      - main

# 以下，jobs の定義
jobs:
  # 「build」という名前のジョブを定義
  build:
    # ubunts の最新版を指定
    runs-on: ubuntu-latest

    # 実行する処理やコマンドを指定
    steps:
      # レポジトリからの checkout を実行
      - uses: actions/checkout@v2
      #      - uses: enriikke/gatsby-gh-pages-action@v2
      #        with:
      #          access-token: ${{ secrets.ACCESS_TOKEN }}
      #          gatsby-args: --prefix-paths
      # Node のセットアップ
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      # Node の実行（npm install, npm run build）
      - name: Build Project
        run: |
          yarn
          # npm install
          npm run build
      # 確認のためのリスト表示　必要なければ削除
      # - name: List output files
      #   run: ls -laFG
      #
      # 以下のサイトを参考に github action で build, netlify へ publicフォルダを転送
      # https://sung.codes/blog/2019/12/25/building-gatsby-with-git-hub-actions-and-deploying-to-netlify/
      - name: Publish using netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=public --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

      # rsync の設定
      - name: rsync deployments to hlc1
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --omit-dir-times --delete
          path: public/
          remote_path: ${{ secrets.REMOTE_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.ID_ECDSA_FREEDOM }}
